name: Telegram Notify

on:
  push:

jobs:
  telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Send push details to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          
          MESSAGE=$(cat <<EOF
          New push!
          *Author:* $GITHUB_ACTOR
          *Branch:* $GITHUB_REF_NAME
          *Commits:*
          EOF
          )
          COMMITS=$(jq -r '.commits[].message' <<< '${{ toJson(github.event) }}')

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MESSAGE $COMMITS" \
            -d parse_mode="Markdown"
